import Navbar from "@/pages/Components/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import ReduxProvider from "@/Redux/ReduxProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
// "use client";
// import React from "react";
// import { Provider } from "react-redux";
// import store from "./Store";

// const ReduxProvider = ({children}) => {
//     return(<Provider store={store}> {children}</Provider>)
// };
// export default ReduxProvider
